"""SSO accounts, approver rules, team email recipients, hosted agent briefs

Revision ID: a1b2c3d4e5f6
Revises: f5dbf8158b62
Create Date: 2026-10-01 14:19:39.781479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = 'f5dbf8158b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_briefs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('client', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_briefs'))
    )
    op.create_index('ix_agent_briefs_created', 'agent_briefs', ['created_at'], unique=False)
    op.add_column('approvals', sa.Column('requested_by_user_id', sa.Uuid(), nullable=True))
    op.add_column('teams', sa.Column('emails', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=16), nullable=False, server_default='password'))
    op.add_column('users', sa.Column('sso_subject', sa.String(length=300), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.create_unique_constraint(op.f('uq_users_sso_subject'), 'users', ['sso_subject'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_sso_subject'), 'users', type_='unique')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.drop_column('users', 'sso_subject')
    op.drop_column('users', 'auth_provider')
    op.drop_column('teams', 'emails')
    op.drop_column('approvals', 'requested_by_user_id')
    op.drop_index('ix_agent_briefs_created', table_name='agent_briefs')
    op.drop_table('agent_briefs')
    # ### end Alembic commands ###
